// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsR4tPAZkDdzOPW7wYzv-7ixQSlCJYHcA',
    appId: '1:341029255599:web:4855ab840d76757274575a',
    messagingSenderId: '341029255599',
    projectId: 'attandance-system-7c718',
    authDomain: 'attandance-system-7c718.firebaseapp.com',
    storageBucket: 'attandance-system-7c718.firebasestorage.app',
    measurementId: 'G-L4P06T0R82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdvve8RhAEhaUvd_vSRszXJrqTZkYGUKQ',
    appId: '1:341029255599:android:f69c27ff800dbb7e74575a',
    messagingSenderId: '341029255599',
    projectId: 'attandance-system-7c718',
    storageBucket: 'attandance-system-7c718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC94dYOXlmeQcZVCGNKinhoZjmgC0yGPpA',
    appId: '1:341029255599:ios:1354524dd09314e374575a',
    messagingSenderId: '341029255599',
    projectId: 'attandance-system-7c718',
    storageBucket: 'attandance-system-7c718.firebasestorage.app',
    iosBundleId: 'com.example.attandanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsR4tPAZkDdzOPW7wYzv-7ixQSlCJYHcA',
    appId: '1:341029255599:web:526148aea516252174575a',
    messagingSenderId: '341029255599',
    projectId: 'attandance-system-7c718',
    authDomain: 'attandance-system-7c718.firebaseapp.com',
    storageBucket: 'attandance-system-7c718.firebasestorage.app',
    measurementId: 'G-J9XZ82XMXC',
  );
}
